apiVersion: apps/v1
kind: Deployment
metadata:
  name: harmony-cron-service
  labels:
    name: harmony-cron-service
spec:
  replicas: 1
  selector:
    matchLabels:
      name: harmony-cron-service
  template:
    metadata:
      labels:
        name: harmony-cron-service
    spec:
      containers:
        - name: harmony-cron-service
          imagePullPolicy: IfNotPresent
          image: $CRON_SERVICE_IMAGE
          resources:
            limits:
              memory: $CRON_SERVICE_LIMITS_MEMORY
              cpu: $CRON_SERVICE_LIMITS_CPU
            requests:
              memory: $CRON_SERVICE_REQUESTS_MEMORY
              cpu: $CRON_SERVICE_REQUESTS_CPU
          envFrom:
          - configMapRef:
              name: cron-service-env
          - secretRef:
              name: harmony-secrets
          ports:
            - containerPort: $PORT
---
apiVersion: v1
kind: Service
metadata:
  name: harmony-cron-service
spec:
  ports:
    - name: frontend
      port: $PORT
      targetPort: $PORT
      protocol: TCP
  selector:
    name: harmony-cron-service
  type: ClusterIP