FROM osgeo/gdal

RUN apt-get update
RUN apt-get -y install python3-pip
RUN pip install jupyter
RUN pip install rasterio OWSLib GDAL matplotlib netCDF4 numpy
RUN pip install s3fs zarr

RUN mkdir -p notebooks
RUN mkdir -p notebooks/tmp
WORKDIR /notebooks
COPY ./docs .
COPY ./config /config

RUN pip install -r notebook_helpers/requirements.txt

ENTRYPOINT notebook_helpers/run-jupyter-docker
