apiVersion: apps/v1
kind: Deployment
metadata:
  name: harmony-small-work-updater
  labels:
    name: harmony-small-work-updater
spec:
  replicas: $SMALL_WORK_UPDATER_POD_REPLICAS
  selector:
    matchLabels:
      name: harmony-small-work-updater
  template:
    metadata:
      labels:
        name: harmony-small-work-updater
    spec:
      containers:
        - name: harmony-small-work-updater
          imagePullPolicy: IfNotPresent
          image: $WORK_ITEM_UPDATER_IMAGE
          resources:
            limits:
              memory: $WORK_ITEM_UPDATER_LIMITS_MEMORY
              cpu: $WORK_ITEM_UPDATER_LIMITS_CPU
            requests:
              memory: $WORK_ITEM_UPDATER_REQUESTS_MEMORY
              cpu: $WORK_ITEM_UPDATER_REQUESTS_CPU
          envFrom:
          - configMapRef:
              name: work-updater-env
          - secretRef:
              name: harmony-secrets
          env:
          - name: WORK_ITEM_UPDATE_QUEUE_TYPE
            value: small
          ports:
            - containerPort: $PORT
---
apiVersion: v1
kind: Service
metadata:
  name: harmony-small-work-updater
spec:
  ports:
    - name: frontend
      port: $PORT
      targetPort: $PORT
      protocol: TCP
  selector:
    name: harmony-small-work-updater
  type: ClusterIP