{
 "title": "Kubernetes Cluster New(Prometheus)-Latest-1",
 "description": "Summary metrics about containers running on Kubernetes nodes.\r\n\r\nDashboard was taken from here.  This version does not reqiure you to\r\nsetup the Kubernetes-app plugin. (https://github.com/grafana/kubernetes-app)\r\n\r\nUse this Helm chart to launch Grafana into a Kubernetes cluster.  It will include this dashboard and many more dashboards to give you visibility into the Kubernetes Cluster. (https://github.com/sekka1/cloud-public/tree/master/kubernetes/pods/grafana-helm)",
 "tags": [
  "kubernetes",
  "kubernetes-app"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "node", "query": ".*" },
   { "name": "namespace", "query": ".*" }
  ]
 },
 "panels": [
  {
   "title": "Cluster Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cluster Pod Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{node=~\"$${hold}node\"}) /(sum(kube_node_info) * 110)"
    }
   ]
  },
  {
   "title": "Cluster CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{node=~\"$${hold}node\"}) / sum(kube_node_status_allocatable{node=~\"$${hold}node\"})"
    }
   ]
  },
  {
   "title": "Cluster Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{node=~\"$${hold}node\"}) / sum(kube_node_status_allocatable{node=~\"$${hold}node\"})"
    }
   ]
  },
  {
   "title": "Cluster Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum (node_filesystem_size_bytes{nodename=~\"$${hold}node\"}) - sum (node_filesystem_free_bytes{nodename=~\"$${hold}node\"})) / sum (node_filesystem_size_bytes{nodename=~\"$${hold}node\"})"
    }
   ]
  },
  {
   "title": "Cluster Pod Capacity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "pods" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_pods{node=~\"$${hold}node\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_capacity_pods{node=~\"$node\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_info{node=~\"$${hold}node\"})",
     "legendFormat": "requested"
    }
   ]
  },
  {
   "title": "Cluster CPU Capacity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{node=~\"$${hold}node\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_allocatable{node=~\"$node\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{node=~\"$${hold}node\"})",
     "legendFormat": "requested"
    }
   ]
  },
  {
   "title": "Cluster Mem Capacity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_memory_bytes{node=~\"$${hold}node\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_capacity{node=~\"$${hold}node\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{node=~\"$${hold}node\"})",
     "legendFormat": "requested"
    }
   ]
  },
  {
   "title": "Cluster Disk Capacity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{nodename=~\"$${hold}node\"}) - sum(node_filesystem_free_bytes{nodename=~\"$${hold}node\"})",
     "legendFormat": "usage"
    },
    {
     "expr": "sum(node_filesystem_size{nodename=~\"$node\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Deployment Replicas - Up To Date",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{namespace=~\"$${hold}namespace\"}",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Deployment Replicas",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{namespace=~\"$${hold}namespace\"})"
    }
   ]
  },
  {
   "title": "Deployment Replicas - Updated",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_updated{namespace=~\"$${hold}namespace\"})"
    }
   ]
  },
  {
   "title": "Deployment Replicas - Unavailable",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"$${hold}namespace\"})"
    }
   ]
  },
  {
   "title": "Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number Of Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_info{node=~'$${dollar}node'})"
    }
   ]
  },
  {
   "title": "Nodes Out of Disk",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"DiskPressure\", node=~\"$${hold}node\", status=\"true\"})"
    }
   ]
  },
  {
   "title": "Nodes Unavailable",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable{node=~\"$${hold}node\"})"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pods Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$${hold}namespace\", phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Pods Pending",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$${hold}namespace\", phase=\"Pending\"})"
    }
   ]
  },
  {
   "title": "Pods Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$${hold}namespace\", phase=\"Failed\"})"
    }
   ]
  },
  {
   "title": "Pods Succeeded",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$${hold}namespace\", phase=\"Succeeded\"})"
    }
   ]
  },
  {
   "title": "Pods Unknown",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$${hold}namespace\", phase=\"Unknown\"})"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Containers Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=~\"$${hold}namespace\"})"
    }
   ]
  },
  {
   "title": "Containers Waiting",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=~\"$${hold}namespace\"})"
    }
   ]
  },
  {
   "title": "Containers Terminated",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated{namespace=~\"$${hold}namespace\"})"
    }
   ]
  },
  {
   "title": "Containers Restarts (Last 30 Minutes)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total[30m])) by (container) > 0"
    }
   ]
  },
  {
   "title": "CPU Cores Requested by Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$${hold}namespace\", node=~\"$${hold}node\"})"
    }
   ]
  },
  {
   "title": "Memory Requested By Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$${hold}namespace\", node=~\"$${hold}node\"})"
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Jobs Succeeded",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_job_status_succeeded{namespace=~\"$${hold}namespace\"})"
    }
   ]
  },
  {
   "title": "Jobs Succeeded",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_job_status_active{namespace=~\"$${hold}namespace\"})"
    }
   ]
  },
  {
   "title": "Jobs Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_job_status_failed{namespace=~\"$${hold}namespace\"})"
    }
   ]
  }
 ]
}