apiVersion: v1
kind: Pod
metadata:
  name: localstack-pod
  labels:
    name: localstack-pod
    app: localstack
spec:
  containers:
    - name: localstack
      image: localstack/localstack:3.0.2
      ports:
        - containerPort: 4566
      volumeMounts:
        - mountPath: /etc/localstack/init/ready.d
          name: localstack-start
      env:
        - name: LOCALSTACK_SERVICES
          value: "lambda,s3,sqs,sts,cloudwatch"
        - name: LOCALSTACK_DEBUG
          value: "1"
  volumes:
    - name: localstack-start
      configMap:
        # Mount startup.sh script created by start-postgres-localstack into the volume
        name: localstack-config
        defaultMode: 0744

---
apiVersion: v1
kind: Service
metadata:
  name: localstack
  labels:
    name: localstack
spec:
  ports:
    - name: "edge"
      port: 4566
      targetPort: 4566
    - name: "s3"
      port: 4572
      targetPort: 4566
    - name: "sts"
      port: 4592
      targetPort: 4566
  selector:
    name: localstack-pod
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: postgres
  name: postgres-config
stringData:
  password: password
  username: postgres
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
      name: postgres
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          value: password
        image: postgres:13-alpine
        name: main
        ports:
        - containerPort: 5432
        readinessProbe:
          exec:
            command:
            - psql
            - -U
            - postgres
            - -c
            - SELECT 1
          initialDelaySeconds: 15
          timeoutSeconds: 2
      nodeSelector:
        kubernetes.io/os: linux
---