FROM node:16-alpine

RUN apk update
RUN apk add bash vim curl git python3 postgresql-client make gcc g++ libc-dev libpq-dev
RUN git config --global url."https://".insteadOf ssh://

RUN mkdir -p /harmony-work-updater
RUN mkdir -p /tmp/metadata
COPY built env-defaults package.json package-lock.json /harmony-work-updater/
WORKDIR /harmony-work-updater
RUN npm ci

ENTRYPOINT [ "node", "kubernetes-services/work-updater/app/server.js"]
