FROM node:16-alpine

RUN apk update
RUN apk add bash vim curl git python3 postgresql-client make gcc g++ libc-dev libpq-dev
RUN git config --global url."https://".insteadOf ssh://

RUN mkdir -p /work-updater/kubernetes-services/work-updater
COPY env-defaults package.json package-lock.json /work-updater/kubernetes-services/work-updater/
COPY built /work-updater/
WORKDIR /work-updater/kubernetes-services/work-updater
RUN npm ci
WORKDIR /work-updater
# This symlink is needed to make module loading work correctly
RUN ln -s kubernetes-services/work-updater/node_modules .
WORKDIR /work-updater/kubernetes-services/work-updater

ENTRYPOINT [ "node", "app/server.js"]