name: Publish Mac service images to DockerHub

on:
  push:
    tags:
      - '*'
    branches:
      - main

env:
  DOCKER_USER: bilts

jobs:
  push:
    runs-on: macos-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.14.x
      - name: Log into registry
        run: echo "${{ secrets.DOCKERHUB }}" | docker login -u "${DOCKER_USER}" --password-stdin
      - name: Setup Node
        run: |
          npm install
      - name: Build and publish images
        run: |
          # For tagged versions, translate e.g. "refs/tags/v1.2.3" -> "1.2.3"
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # build and publish images for all services
          VERSION="${VERSION}-arm64" lerna run build
          VERSION="${VERSION}-arm64" lerna run publish

